import React,{useRef,useState} from 'react';
import Card from './Card';
function Foreground()  {
  const ref=useRef(null);

  const data=[
    {
      desc:"This is a sample file code generated by Eshwar",
      filesize:".9mb",
      close:true,
      tag:{ isOpen:true,tagTitle:"Download Now", tagColor:"green"},
    },
    {
      desc:"This is a sample file code generated by Eshwar",
      filesize:".9mb",
      close:true,
      tag:{ isOpen:true,tagTitle:"Download Now", tagColor:"blue"},
    },
    {
      desc:"This is a sample file code generated by Eshwar",
      filesize:".9mb",
      close:true,
      tag:{ isOpen:true,tagTitle:"Download Now", tagColor:"green"},
    },
  ];
  return (
    <div ref={ref} className='fixed top-0 left-0 z-[3] w-full h-screen flex gap-10 flex-wrap p-5 '>
      {data.map((item,index)=>(
        <Card data={item} reference={ref}/>
      ))}
      <h4 className='text-zinc-400 ml-[900px] mt-[920px]'>Designed By Eshwar</h4>
    </div>
  );
}

export default Foreground;
